dist: trusty
sudo: required
language: go

go_import_path: github.com/contiv/vpp

go:
  - 1.9.x

cache:
  directories:
    - $HOME/build-cache

env:
  - GO_BUILD_TAGS=mockvpp

before_install:
  - go get -v github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - sudo apt-get install npm && npm install -g markdown-link-check

script:
  - make check_links || true
  - make check_format
  - make lint
  - make
  - make test-cover

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
